name: CMake

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        compiler: ["g", "clang"]
        gversion: [0, 12, 13]
        cversion: [0, 14, 15, 16]
        libcxx: ["OFF", "ON"]
        exclude:
          - libcxx: "ON"
            compiler: "g"
          - gversion: 0
            libcxx: "OFF"
          - gversion: 12
            libcxx: "ON"
          - gversion: 13
            libcxx: "ON"
          - cversion: 0
            compiler: "clang"
          - cversion: 14
            compiler: "g"
          - cversion: 15
            compiler: "g"
          - cversion: 16
            compiler: "g"

    steps:
    - uses: actions/checkout@v3

    - name: Install Packages
      run: |
        sudo apt-get -q update
        sudo apt-get install cmake
        cmake --version

    - name: Install GCC Packages
      if: ${{ matrix.libcxx == 'OFF' }}
      run: |
        sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
        sudo apt-get -q update
        sudo apt-get install gcc-${{ matrix.gversion }} g++-${{ matrix.gversion }}
        sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-${{ matrix.gversion }} ${{ matrix.gversion }}0 --slave /usr/bin/g++ g++ /usr/bin/g++-${{ matrix.gversion }} --slave /usr/bin/gcov gcov /usr/bin/gcov-${{ matrix.gversion }}
        g++ -v

    - name: Install Clang Packages
      if: ${{ matrix.compiler == 'clang' }}
      run: |
        sudo bash -c "wget -qO- https://apt.llvm.org/llvm-snapshot.gpg.key | tee /etc/apt/trusted.gpg.d/apt.llvm.org.asc"
        sudo add-apt-repository -y "deb http://apt.llvm.org/$(lsb_release -s -c)/ llvm-toolchain-$(lsb_release -s -c)-${{ matrix.cversion }} main"
        sudo apt-get -q update
        sudo apt-get install clang-${{ matrix.cversion }} libc++-${{ matrix.cversion }}-dev libc++abi-${{ matrix.cversion }}-dev
        sudo update-alternatives --remove-all clang
        sudo update-alternatives --remove-all clang++
        sudo update-alternatives --install /usr/bin/clang clang /usr/bin/clang-${{ matrix.cversion }} ${{ matrix.cversion }}0 --slave /usr/bin/clang++ clang++ /usr/bin/clang++-${{ matrix.cversion }}
        clang++ -v

    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -DCMAKE_CXX_COMPILER=${{ matrix.compiler }}++ -DCARDPILE_USE_LIBCXX=${{ matrix.libcxx }}

    - name: Build
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}

    - name: Test
      working-directory: ${{github.workspace}}/build
      run: ctest -C ${{env.BUILD_TYPE}}

